services:
  paper: 
    build:
      context: .docker
      dockerfile: Dockerfile
      args:
        JAVA_IMAGE: eclipse-temurin:17-jre-jammy@sha256:475d8e96b4b2bfe08999e5e854755c773af1581acdf959a4545d88f0696a2339
        PAPERMC_PROJECT: paper
        PAPERMC_VERSION: 1.20.4
        PAPERMC_BUILD: 499
        PAPERMC_DOWNLOAD_URL: https://fill-data.papermc.io/v1/objects/cabed3ae77cf55deba7c7d8722bc9cfd5e991201c211665f9265616d9fe5c77b/paper-1.20.4-499.jar
        PAPERMC_DOWNLOAD_SHA256: cabed3ae77cf55deba7c7d8722bc9cfd5e991201c211665f9265616d9fe5c77b
        JVM_FLAGS: |
          -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200
          -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch
          -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M
          -XX:G1ReservePercent=20 -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4
          -XX:InitiatingHeapOccupancyPercent=15 -XX:G1MixedGCLiveThresholdPercent=90
          -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem
          -XX:MaxTenuringThreshold=1 -Dusing.aikars.flags=https://mcflags.emc.gs -Daikars.new.flags=true
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "25565"]
      interval: 3s
      timeout: 3s
      retries: 3
    tty: true
    stdin_open: true
    environment:
      - SERVER_MEMORY=4G
    ports:
      - "25565:25565"
    volumes:
      - ./server/paper:/home/minecraft

  velocity: 
    build:
      context: .docker
      dockerfile: Dockerfile
      args:
        JAVA_IMAGE: eclipse-temurin:21-jre-jammy@sha256:d63bd8d9b171999cbed8576f2c76e874dd4856791a358536e5c4d407e77edc13
        PAPERMC_PROJECT: velocity
        PAPERMC_VERSION: 3.5.1
        PAPERMC_BUILD: 615
        PAPERMC_DOWNLOAD_URL: https://fill-data.papermc.io/v1/objects/b4e3164df5377346854dc6cb9e6a78022b1946ff69e89676313f5f6f1c6f0fb3/velocity-3.5.1-615.jar
        PAPERMC_DOWNLOAD_SHA256: b4e3164df5377346854dc6cb9e6a78022b1946ff69e89676313f5f6f1c6f0fb3
        JVM_FLAGS: |
          -XX:+AlwaysPreTouch -XX:+ParallelRefProcEnabled -XX:+UnlockExperimentalVMOptions
          -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:MaxInlineLevel=15
    healthcheck:
      test: ["CMD", "nc", "-z", "127.0.0.1", "25577"]
      interval: 3s
      timeout: 3s
      retries: 3
    tty: true
    stdin_open: true
    environment:
      - SERVER_MEMORY=2G
    ports:
      - "25577:25577"
    volumes:
      - ./server/velocity:/home/minecraft
