name: Build Velocity Docker image
description: Build a Docker image for Velocity

inputs:
  token:
    description: secrets.GITHUB_TOKEN
    required: true
  jre-version:
    description: "Java version to use"
    required: false
    default: "21"
  version:
    description: "Velocity version to build"
    required: false
    default: "latest"
 
runs: 
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .docker
        push: true
        tags: ghcr.io/${{ github.repository }}/velocity:${{ inputs.version }}
        build-args: |
          JAVA_VERSION=${{ inputs.jre-version }}
          PAPERMC_APP_NAME=velocity
          PAPERMC_APP_VERSION=${{ inputs.version }}
          JVM_FLAGS=-XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:MaxInlineLevel=15
        platforms: linux/amd64,linux/arm64