name: Target 1.20.4

on:
  workflow_dispatch:

jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/paper
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 1.20.4