name: Target Latest

on:
  workflow_dispatch:

jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/paper
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
  velocity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/velocity
        with:
          token: ${{ secrets.GITHUB_TOKEN }}