name: Target Latest

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1,15 * *'  # 毎月1日と15日の午前0時に実行

jobs:
  paper:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/paper
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
  velocity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/velocity
        with:
          token: ${{ secrets.GITHUB_TOKEN }}